### ISSUE TITLE
Fix Control access issue on GET and POST data

### ISSUE THREAD

**Issue by fcasaloti-student** [fabioturazzidouglas/Hackermen_Project#45]
Daniil, Fabio, please, fix the Access Control on your GET and POST data. Please insert the following statement in the beggining of each GET and POST.
Today, if a user does not have either a valid session or a valid userType attribute, the Page return an error message that a null value is found when it can try to get the attribute.

Customer Users:

		// Check if user is logged in and if it is a Customer
		if (!user.hasValidSession(session))
			return "denied";
		else if (!session.getAttribute("userType").equals("Customer"))
			return "denied";

Staff Users:
		// Check if user is logged in and if it is a Customer
		if (!user.hasValidSession(session))
			return "denied";
		else if (!session.getAttribute("userType").equals("Staff"))
			return "denied";

**Comment by fabioturazzidouglas** [comment]
Fixed it to roomSearch, now it only allows customers to access
